name: remote ssh command
on: 
  push:
    branches:
      - sendMail
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password

      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd pruebas_github_actions
          foldername="helpdesk-${{ github.run_number }}"
          mkdir $foldername && cd $foldername
          github_url="https://github.com/${{ github.repository }}"
          git clone $github_url
          cd helpdesk 
          virtualenv venv 
          source venv/bin/activate
          pip install -r requirements.txt
          cp ../../.env ./helpdesk/.env
          python manage.py migrate 
          python manage.py runserver 0.0.0.0:8000