name: remote ssh command
on: 
  push:
    branches:
      - sendMail
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      env:
          FOLDERNAME: ${{ github.repository }} - ${{ github.run_number }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd pruebas_github_actions
          var="helpdesk-${{ github.run_number }}"
          mkdir $var && cd $var